version: '3.3'
services:

  pokemon-database:
    container_name: pokemon-database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pokemon'
      MYSQL_USER: 'micro'
      MYSQL_PASSWORD: 'service'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
